name: Scrape and Deploy

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 mins
  workflow_dispatch:

jobs:
  scrape_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Scrape and Build
        run: |
          python scrape.py
